name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["main", "develop"]
    paths-ignore: ["README.md"]
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths-ignore: ["README.md"]

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        stack-name: [local]
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    env:
      ZENML_DEBUG: true
      ZENML_ANALYTICS_OPT_IN: false
      ZENML_LOGGING_VERBOSITY: INFO
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run tests
        uses: ./.github/actions/starter_template_test
        with:
          stack-name: ${{ matrix.stack-name }}
          python-version: ${{ matrix.python-version }}
